# name: Deploy to Vercel with DB Setup

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'  # Adjust this to your project's Node.js version

#       - name: Install dependencies
#         run: npm ci

#       - name: Run database migrations
#         run: npx sequelize-cli db:migrate
#         env:
#           DATABASE_URL: ${{ secrets.DATABASE_URL }}

#       - name: Run database seeds
#         run: npx sequelize-cli db:seed:all
#         env:
#           DATABASE_URL: ${{ secrets.DATABASE_URL }}

#       - name: Install Vercel CLI
#         run: npm install --global vercel@latest

#       - name: Pull Vercel Environment Information
#         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Build Project Artifacts
#         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
#       - name: Deploy Project Artifacts to Vercel
#         run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}