name: CI/CD

on:
  push:
    branches: [ prod ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install dependencies
      run: |
        npm ci
        cd client && npm ci

    - name: Build React app
      run: |
        cd client
        npm run build
      env:
        CI: false

    - name: Deploy to FastComet
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FASTCOMET_FTP_SERVER }}
        username: ${{ secrets.FASTCOMET_FTP_USERNAME }}
        password: ${{ secrets.FASTCOMET_FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/convo.akoplus.co.nz/